"""bi semantic model: native metric expressions

Revision ID: 13140b4c3793
Revises: 5bb07828d804
Create Date: 2026-09-23 09:54:10.974799
"""
from alembic import op
import sqlalchemy as sa


revision = '13140b4c3793'
down_revision = '5bb07828d804'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('native_expression', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('native_language', sa.String(length=16), nullable=True))
        # server_default so existing metrics get a value; every pre-existing metric is SQL-native
        batch_op.add_column(sa.Column('is_computable', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('source_system', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.drop_column('source_system')
        batch_op.drop_column('is_computable')
        batch_op.drop_column('native_language')
        batch_op.drop_column('native_expression')

    # ### end Alembic commands ###
