"""multi-mode auth: source credentials + pending flows

Revision ID: 3e55f5b76f67
Revises: 97842dad8a64
Create Date: 2026-10-08 21:48:24.563802
"""
from alembic import op
import sqlalchemy as sa


revision = '3e55f5b76f67'
down_revision = '97842dad8a64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    existing = set(sa.inspect(op.get_bind()).get_table_names())
    have = {c["name"] for c in sa.inspect(op.get_bind()).get_columns("data_sources")}
    # ### commands auto generated by Alembic - please adjust! ###
    if 'pending_auth' not in existing:
        op.create_table('pending_auth',
        sa.Column('state', sa.String(length=64), nullable=False),
        sa.Column('source_id', sa.String(length=32), nullable=False),
        sa.Column('mode', sa.String(length=32), nullable=False),
        sa.Column('payload_enc', sa.Text(), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('state')
        )
        with op.batch_alter_table('pending_auth', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_pending_auth_source_id'), ['source_id'], unique=False)

    if 'source_credentials' not in existing:
        op.create_table('source_credentials',
        sa.Column('source_id', sa.String(length=32), nullable=False),
        sa.Column('kind', sa.String(length=16), nullable=False),
        sa.Column('secret_enc', sa.Text(), nullable=False),
        sa.Column('refresh_enc', sa.Text(), nullable=True),
        sa.Column('username', sa.String(length=255), nullable=True),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('scopes', sa.JSON(), nullable=False),
        sa.Column('meta', sa.JSON(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('source_id')
        )
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        # server_default: every pre-existing source already authenticates exactly the way
        # the 'credentials' mode describes, so they migrate with no re-entry.
        if 'auth_mode' not in have:
            batch_op.add_column(sa.Column('auth_mode', sa.String(length=32), nullable=False, server_default='credentials'))
        if 'auth_config' not in have:
            batch_op.add_column(sa.Column('auth_config', sa.JSON(), nullable=False, server_default='{}'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_column('auth_config')
        batch_op.drop_column('auth_mode')

    op.drop_table('source_credentials')
    with op.batch_alter_table('pending_auth', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_auth_source_id'))

    op.drop_table('pending_auth')
    # ### end Alembic commands ###
