"""initial schema

Revision ID: 5bb07828d804
Revises: 
Create Date: 2026-09-21 19:53:46.279014
"""
from alembic import op
import sqlalchemy as sa


revision = '5bb07828d804'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_provider_configs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sa.String(length=128), nullable=True),
    sa.Column('purposes', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('input_cost_per_1m', sa.Float(), nullable=False),
    sa.Column('output_cost_per_1m', sa.Float(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ai_usage',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('conversation_id', sa.String(length=32), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=True),
    sa.Column('resource_id', sa.String(length=32), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('data_sources',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('refresh_frequency', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('read_only', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('health', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_sources_type'), ['type'], unique=False)

    op.create_table('embeddings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('object_type', sa.String(length=32), nullable=False),
    sa.Column('object_id', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_type', 'object_id')
    )
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_embeddings_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_embeddings_object_type'), ['object_type'], unique=False)

    op.create_table('entities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('glossary_terms',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('term', sa.String(length=128), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=128), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('synonyms', sa.JSON(), nullable=False),
    sa.Column('related_terms', sa.JSON(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term')
    )
    op.create_table('insights',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('metric_id', sa.String(length=32), nullable=True),
    sa.Column('period', sa.String(length=32), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_kind'), ['kind'], unique=False)

    op.create_table('permissions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('resource_type', sa.String(length=16), nullable=False),
    sa.Column('resource_id', sa.String(length=32), nullable=False),
    sa.Column('access', sa.String(length=8), nullable=False),
    sa.Column('row_filter', sa.Text(), nullable=True),
    sa.Column('mask_columns', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_role'), ['role'], unique=False)

    op.create_table('query_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ref', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('source_id', sa.String(length=32), nullable=True),
    sa.Column('conversation_id', sa.String(length=32), nullable=True),
    sa.Column('sql', sa.Text(), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result_preview', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref')
    )
    with op.batch_alter_table('query_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_query_log_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_log_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_log_user_id'), ['user_id'], unique=False)

    op.create_table('semantic_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('object_type', sa.String(length=32), nullable=False),
    sa.Column('object_id', sa.String(length=32), nullable=False),
    sa.Column('object_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.String(length=255), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('previous', sa.JSON(), nullable=True),
    sa.Column('current', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('semantic_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_semantic_versions_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_semantic_versions_object_type'), ['object_type'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('conversations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('is_saved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('datasets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_domain', sa.String(length=128), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('sensitivity', sa.String(length=32), nullable=False),
    sa.Column('refresh_frequency', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_business_domain'), ['business_domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_source_id'), ['source_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('tables',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('dataset_id', sa.String(length=32), nullable=False),
    sa.Column('schema_name', sa.String(length=255), nullable=True),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_domain', sa.String(length=128), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_profiled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_column', sa.String(length=255), nullable=True),
    sa.Column('ai_suggestion', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tables_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tables_table_name'), ['table_name'], unique=False)

    op.create_table('columns',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('table_id', sa.String(length=32), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.String(length=128), nullable=False),
    sa.Column('logical_type', sa.String(length=32), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_definition', sa.Text(), nullable=True),
    sa.Column('semantic_type', sa.String(length=64), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('is_primary_key', sa.Boolean(), nullable=False),
    sa.Column('is_foreign_key', sa.Boolean(), nullable=False),
    sa.Column('is_nullable', sa.Boolean(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('sensitivity', sa.String(length=16), nullable=False),
    sa.Column('pii_type', sa.String(length=32), nullable=True),
    sa.Column('sample_values', sa.JSON(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('ai_suggestion', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'column_name')
    )
    with op.batch_alter_table('columns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_columns_table_id'), ['table_id'], unique=False)

    op.create_table('metrics',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('table_id', sa.String(length=32), nullable=True),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('filters', sa.Text(), nullable=True),
    sa.Column('date_column', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('domain', sa.String(length=128), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('related_metrics', sa.JSON(), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metrics_table_id'), ['table_id'], unique=False)

    op.create_table('table_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('table_id', sa.String(length=32), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_signature', sa.Text(), nullable=False),
    sa.Column('max_date', sa.String(length=64), nullable=True),
    sa.Column('profiled_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('table_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_table_profiles_table_id'), ['table_id'], unique=False)

    op.create_table('data_quality_issues',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('table_id', sa.String(length=32), nullable=True),
    sa.Column('column_id', sa.String(length=32), nullable=True),
    sa.Column('rule', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['columns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_quality_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_quality_issues_rule'), ['rule'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_quality_issues_table_id'), ['table_id'], unique=False)

    op.create_table('entity_mappings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('column_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('transform', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['column_id'], ['columns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'column_id')
    )
    with op.batch_alter_table('entity_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_mappings_column_id'), ['column_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_mappings_entity_id'), ['entity_id'], unique=False)

    op.create_table('relationships',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('from_column_id', sa.String(length=32), nullable=False),
    sa.Column('to_column_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_cross_source', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_column_id'], ['columns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_column_id'], ['columns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.create_index('ix_rel_cols', ['from_column_id', 'to_column_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationships_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationships_status'))
        batch_op.drop_index('ix_rel_cols')

    op.drop_table('relationships')
    with op.batch_alter_table('entity_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_mappings_entity_id'))
        batch_op.drop_index(batch_op.f('ix_entity_mappings_column_id'))

    op.drop_table('entity_mappings')
    with op.batch_alter_table('data_quality_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_quality_issues_table_id'))
        batch_op.drop_index(batch_op.f('ix_data_quality_issues_rule'))

    op.drop_table('data_quality_issues')
    with op.batch_alter_table('table_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_table_profiles_table_id'))

    op.drop_table('table_profiles')
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metrics_table_id'))

    op.drop_table('metrics')
    with op.batch_alter_table('columns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_columns_table_id'))

    op.drop_table('columns')
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tables_table_name'))
        batch_op.drop_index(batch_op.f('ix_tables_dataset_id'))

    op.drop_table('tables')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_source_id'))
        batch_op.drop_index(batch_op.f('ix_datasets_business_domain'))

    op.drop_table('datasets')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_user_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('semantic_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_semantic_versions_object_type'))
        batch_op.drop_index(batch_op.f('ix_semantic_versions_object_id'))

    op.drop_table('semantic_versions')
    with op.batch_alter_table('query_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_query_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_query_log_source_id'))
        batch_op.drop_index(batch_op.f('ix_query_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_query_log_conversation_id'))

    op.drop_table('query_log')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_role'))
        batch_op.drop_index(batch_op.f('ix_permissions_resource_id'))

    op.drop_table('permissions')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_kind'))

    op.drop_table('jobs')
    op.drop_table('insights')
    op.drop_table('glossary_terms')
    op.drop_table('entities')
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_embeddings_object_type'))
        batch_op.drop_index(batch_op.f('ix_embeddings_object_id'))

    op.drop_table('embeddings')
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_sources_type'))

    op.drop_table('data_sources')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_created_at'))

    op.drop_table('ai_usage')
    op.drop_table('ai_provider_configs')
    # ### end Alembic commands ###
