"""unified api keys

Revision ID: 9560ffa3b304
Revises: 3e55f5b76f67
Create Date: 2026-10-08 22:00:28.334494
"""
from alembic import op
import sqlalchemy as sa


revision = '9560ffa3b304'
down_revision = '3e55f5b76f67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # backend/main.py runs create_all() on startup, so on a running instance this table
    # may already exist; a plain create_table would abort the migration.
    if 'api_keys' in set(sa.inspect(op.get_bind()).get_table_names()):
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('rate_limit_per_min', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))

    op.drop_table('api_keys')
    # ### end Alembic commands ###
